---
spring:
  application:
    name: coffee
  config:
    activate:
      on-profile: dev
  cloud:
      services:
        registrationMethod: route
        
security:
  basic:
    enabled: false

management:
  security:
    enabled: false