spring:
  config:
    name: configserver
  
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/rahulkj/application-config
          username: 
          password: 

server:
  port: 8888

management:
  context_path: /admin
  security:
    enabled: false